import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { ReconciliationResult } from "./types";

function money(n: number): string {
  return n.toLocaleString("en-US", { style: "currency", currency: "USD" });
}

export function buildReconciliationPdf(opts: {
  creatorName: string;
  source: "demo" | "live";
  result: ReconciliationResult;
  auditChainHead: string | null;
}): jsPDF {
  const { creatorName, source, result, auditChainHead } = opts;
  const doc = new jsPDF();
  const isShort = result.delta > 0;

  doc.setFontSize(18);
  doc.text("PageReal — Earnings Reconciliation", 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Creator: ${creatorName}${source === "demo" ? " (demo account — synthetic data)" : ""}`, 14, 28);
  doc.text(`Period: ${result.periodStart} → ${result.periodEnd}`, 14, 33);
  doc.text(`Generated: ${new Date().toISOString()}`, 14, 38);

  autoTable(doc, {
    startY: 45,
    head: [["Gross earned", "Deductions", "Expected payout", "Actual received", "Difference"]],
    body: [
      [
        money(result.grossEarned),
        money(result.deductions),
        money(result.expectedPayout),
        money(result.actualReceived),
        `${money(Math.abs(result.delta))} ${isShort ? "underpaid" : "matched/overpaid"}`,
      ],
    ],
    theme: "grid",
    headStyles: { fillColor: [15, 23, 42] },
  });

  const afterSummaryY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;

  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text("Period breakdown", 14, afterSummaryY + 10);

  autoTable(doc, {
    startY: afterSummaryY + 14,
    head: [["Period", "Gross", "Expected", "Received", "Delta"]],
    body: result.lineItems.map((item) => [
      `${item.periodStart} -> ${item.periodEnd}`,
      money(item.grossEarned),
      money(item.expectedPayout),
      money(item.actualReceived),
      money(item.delta),
    ]),
    theme: "striped",
    styles: { fontSize: 8 },
    headStyles: { fillColor: [15, 23, 42] },
  });

  const afterTableY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;

  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(`Audit chain head: ${auditChainHead ?? "n/a"}`, 14, afterTableY + 10);
  doc.text(
    "This document is generated by PageReal, an independent creator-side audit tool. It does not depend on or originate from any agency CRM.",
    14,
    afterTableY + 15,
    { maxWidth: 180 }
  );

  return doc;
}
